### PR TITLE
Context reporting for HTML reports

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
(I need to add some more tests for contexts_by_lineno I think)

**Comment by strichter** [comment]
@nedbat I was surprised of you making a PR here, but I guess there is no other way to add to my PR on your repo, eh? Do you want me to do anything special with this PR other than merge it in and add it to the PR on your repo?

**Comment by nedbat** [comment]
Let's leave this open for discussion if needed. I'm going to be adding some tests.

I guess I could have made "suggestions" on the original PR, but that wouldn't give me the code in my own working tree.

**Comment by nedbat** [comment]
I'll add these commits in the main repo.

**Pull request closed without merging**
